{% set name = "open-exchange" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/open_exchange-{{ version }}.tar.gz
  sha256: 35b737cc522a2ec004baf9e4740a79f74d78b8a8f92895a02c7f605e024a9245

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - python >=3.6.2
  host:
    - python >=3.6.2,<4.0.0
    - flit-core >=3.2,<4
    - poetry-core
    - pip
  run:
    - python >=3.6.2,<4.0.0
    - cached-property >=1.5.2
    - pydantic >=1.9.2
    - requests >=2.27.1
    - urllib3 >=1.21.1

test:
  imports:
    - open_exchange
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/opendoor-labs/open-exchange-python
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Open Exchange Python SDK.
  doc_url: https://openexchange.readme.io/

extra:
  recipe-maintainers:
    - chrisguillory
